name: t_overlay_notification
description: A reusable Flutter notification overlay for success, error, warning, and info messages.


version: 1.1.4

# Follow the semantic versioning guidelines:
#
#  Major changes that break backward compatibility: 1.0.0 -> 2.0.0
#  Minor changes: 1.0.0 -> 1.1.0
#  Patches or bug fixes: 1.0.0 -> 1.0.1


homepage: https://github.com/CodingwithTea/t_overlay_notification
repository: https://github.com/CodingwithTea/t_overlay_notification
issue_tracker: https://github.com/CodingwithTea/t_overlay_notification/issues

environment:
  sdk: '>=3.0.0 <4.0.0'    # Allows anyone with Flutter 3.10+ to use it
  flutter: ">=3.10.0"      # Matches the Dart 3.0 requirement

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

