name: t_overlay_notification
description: A reusable Flutter notification overlay for success, error, warning, and info messages.


version: 1.1.3

# Follow the semantic versioning guidelines:
#
#  Major changes that break backward compatibility: 1.0.0 -> 2.0.0
#  Minor changes: 1.0.0 -> 1.1.0
#  Patches or bug fixes: 1.0.0 -> 1.0.1


homepage: https://github.com/CodingwithTea/t_overlay_notification
repository: https://github.com/CodingwithTea/t_overlay_notification
issue_tracker: https://github.com/CodingwithTea/t_overlay_notification/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

